import LeftSideBar from "./components/ui/LeftSideBar";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toast";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Wrapper from "./components/ui/Wrapper";
import Container from "./components/ui/Container";
import TopBar from "./components/ui/TopBar";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable}  h-full antialiased  text-zinc-800`}
    >
      <body className="min-h-full flex flex-col ">
        <Wrapper>
          <Container>
            <div className="flex gap-4">
              <LeftSideBar />
              <div className="flex-1">
                <TopBar />
                {children}
              </div>
            </div>
          </Container>
        </Wrapper>
        <Toaster />
      </body>
    </html>
  );
}
